let etapas = [
   {
      "titulo":"VEREADOR",
      "numeros":5,
      "candidatos":[
         {
            "numero":'38111',
            "nome":"Executiva",
            "partido":"Sentinelas",
            "fotos":[
               {
                  "url":"executiva.png",
                  "legenda":"Vereador",
                  "small":false
               }
            ]
         },
         {
            "numero":'77222',
            "nome":"Mediador",
            "partido":"Diplomatas",
            "fotos":[
               {
                  "url":"mediador.png",
                  "legenda":"Vereador"
               }
            ]
         }
      ]
   },
   {
      "titulo":"PREFEITO",
      "numeros":2,
      "candidatos":[
         {
            "numero":'99',
            "nome":"Comandante",
            "partido":"Analistas",
            "vice":"Logico",
            "fotos":[
               {
                  "url":"comandante.png",
                  "legenda":"Prefeito"
               },
               {
                  "url":"logico.png",
                  "legenda":"Vice-prefeito",
                  "small":true
               }
            ]
         },
         {
            "numero":'33',
            "nome":"Empresario",
            "partido":"Exploradores",
            "vice":"Virtuoso",
            "fotos":[
               {
                  "url":"empresario.png",
                  "legenda":"Prefeito"
               },
               {
                  "url":"virtuoso.png",
                  "legenda":"Vice-prefeito",
                  "small":true
               }
            ]
         }
      ]
   }
]